#!/usr/bin/env bash
# Configure nginx with a redirection rule
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > 404.html
mv 404.html /var/www/html/
redirection_rule="\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
not_found_location="\n\n\tlocation /404.html {\n\t\tinternal;\n\t}"
error_directive="\n\n\terror_page 404 /404.html;"
not_found="$error_directive$not_found_location"

old_string="server_name _";
sed -i "/$old_string/a \ $redirection_rule\t$not_found" /etc/nginx/sites-available/default
service nginx start
