#!/usr/bin/env bash
# Tell the story of the /etc/passwd file
IFS=:
input="/etc/passwd"
while read -r username password uid guid info home shell
do
	echo -n "The user $username is part of the $guid gang, "
	echo -n "lives in $home and rides $shell. "
	echo -n "$uid's place is protected by the passcode $password, "
	echo "more info about the user here: $info"
done < "$input"
