#!/usr/bin/env bash
# Display the IP along with the HTTP status code from the Apache log file
# Display them sorted along with number of occurances
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -r
